Improve "Hacking Wifi with Deauthentification Attack"
iScsc/blog.iscsc.fr pull request #90
Opened 2024-10-15 14:30 UTC by ctmbl

Fix typos, errors and approximations

2024-10-15 15:10 UTC, ctmbl reviewed
@Clems1236 @ViSaN2k 
any comments on the title/summary improvements?

2024-10-23 17:37 UTC, Clems1236 requested changes

2024-10-23 17:37 UTC, Clems1236 commented on src/content/posts/wifi-deauth-attack.md/index.md
> +4) Get the password "hash" when it tries to reconnect to WiFi
5) Get the MIC (Message Integrity Code) wich is a **hash** of several knownable informations included in the network capture and **password**
See the **4 Way Handshake** article for more informations

2024-10-27 21:57 UTC, Clems1236 commented on src/content/posts/wifi-deauth-attack.md/index.md
> +Windows OS doesn't follow the rule and try to reconnect instantly (prefer Windows station to attack if you have the choice :wink:)
No source available online, just test & try observations

2024-10-27 22:07 UTC, Clems1236 approved these changes
temporary approve

2024-12-06 19:18 UTC, merged